### ISSUE TITLE
callout boxes are not rendered in html

### ISSUE THREAD

**Issue by uli-f** [ldeluigi/markdown-docs#227] opened 2024-07-02 02:55 UTC
Github flavored markdown support callout boxes such as:

```
> [!WARNING]
> Text goes here.
```

> [!WARNING]
> Text goes here.

```
> [!IMPORTANT]
> Text goes here.
```

> [!IMPORTANT]
> Text goes here.

```
> [!WARNING]
> Text goes here.
```

> [!WARNING]
> Text goes here.

These callouts are currently not rendered in the html output:

![image](https://github.com/ldeluigi/markdown-docs/assets/98144814/99aa333e-04e4-4a82-b159-796d2bee0b72)

I'd appreciate it if this could be supported.

**Comment by uli-f** [comment] 2024-07-18 01:20
I am using version `ldeluigi/markdown-docs@v0.8.0` in my github workflow. Unfortunately, the callouts do not get properly rendered in HTML for me.

Here is my callout in markdown:

```
> [!WARNING]
> Please note that there are additional fields.
```
And this is how it looks in the generated html:

![image](https://github.com/user-attachments/assets/fd21cd1f-8a30-4f08-b46d-d5f2cd774620)

Let me know if there is anything else that I can provide to support investigating this.

**Comment by uli-f** [comment] 2024-09-10 01:51
@ldeluigi Do you have any updates on this?

**Comment by ldeluigi** [comment] 2024-09-10 07:59
I've tested on my pc, from the master branch:

### input
```markdown

> [!INFO] Title
> An information callout from Obsidian
> inspired by the syntax from the Microsoft Docs

> [!WARNING]
> Please note that there are additional fields.
```

### output
![image](https://github.com/user-attachments/assets/02d028ad-ec61-43ab-a260-0265bf2cb6e9)



I can't reproduce your issue

**Comment by ldeluigi** [comment] 2024-09-10 08:03
If it's fixed, please close the issue, thanks

**Comment by uli-f** [comment] 2024-09-10 08:47
@ldeluigi Thank you for your feedback.

I updated to `ldeluigi/markdown-docs@v0.8.1` and re-ran my workflow.

This is how the action is getting called:
```
      - name: ⚙️ Generate HTML from Markdown
        uses: ldeluigi/markdown-docs@v0.8.1
        with:
          # scans entire repository recursively for markdown files
          src: ./build/docs/md-to-html/markdown
          # writes output files to this directory, will be emptied automatically
          dst: ./build/docs/md-to-html/readme-html
          title: Readme
          language: en
          icon: file-document-outline
          hide-repository: true
```

This is one of my callouts:

```
> [!NOTE]
> It is **strongly recommended** to check the log files after each run to assess if any issues were encountered. 
```

This is how it looks like in the generated html:
![image](https://github.com/user-attachments/assets/56255bc9-fb88-4e14-934d-ddc7e9a25503)

This is the html source:
```
<blockquote>
<p>[!NOTE]
It is <strong>strongly recommended</strong> to check the log files generated by Bloxo after each run to assess if any issues were encountered. </p>
</blockquote>
```

As part of the workflow a docker image is pulled. Looking at the tag, it seems a pretty old version of that docker image is pulled:
```
2024-09-10T08:25:35.2039327Z ##[group]Pull down action image 'deloo/markdown-docs:0.6.7'
2024-09-10T08:25:35.2084810Z ##[command]/usr/bin/docker pull deloo/markdown-docs:0.6.7
2024-09-10T08:25:35.5860798Z 0.6.7: Pulling from deloo/markdown-docs
2024-09-10T08:25:35.5862050Z c158987b0551: Pulling fs layer
2024-09-10T08:25:35.5862790Z 7ec3a91b66d9: Pulling fs layer
2024-09-10T08:25:35.5863586Z 2a66ef9569bf: Pulling fs layer
2024-09-10T08:25:35.5864477Z 51ba2aaea185: Pulling fs layer
2024-09-10T08:25:35.5865422Z 4fe55734f00f: Pulling fs layer
2024-09-10T08:25:35.5866143Z cb6ed86980e0: Pulling fs layer
2024-09-10T08:25:35.5867015Z 897ff19824a2: Pulling fs layer
2024-09-10T08:25:35.5867816Z 2d2a69b423bd: Pulling fs layer
2024-09-10T08:25:35.5868710Z 5b412bbde264: Pulling fs layer
2024-09-10T08:25:35.5869645Z a4ae34314a30: Pulling fs layer
2024-09-10T08:25:35.5870431Z 343c503f69a2: Pulling fs layer
2024-09-10T08:25:35.5871293Z 4823297a760e: Pulling fs layer
2024-09-10T08:25:35.5872205Z 70bed83a25c4: Pulling fs layer
2024-09-10T08:25:35.5872893Z b8cc3c3a30cf: Pulling fs layer
2024-09-10T08:25:35.5873769Z df41b3ea5e95: Pulling fs layer
2024-09-10T08:25:35.5874546Z f41993bcef51: Pulling fs layer
2024-09-10T08:25:35.5875269Z 51ba2aaea185: Waiting
2024-09-10T08:25:35.5876085Z 4fe55734f00f: Waiting
2024-09-10T08:25:35.5876743Z cb6ed86980e0: Waiting
2024-09-10T08:25:35.5877468Z 897ff19824a2: Waiting
2024-09-10T08:25:35.5878303Z 2d2a69b423bd: Waiting
2024-09-10T08:25:35.5878966Z 5b412bbde264: Waiting
2024-09-10T08:25:35.5879650Z a4ae34314a30: Waiting
2024-09-10T08:25:35.5880496Z 343c503f69a2: Waiting
2024-09-10T08:25:35.5881190Z 4823297a760e: Waiting
2024-09-10T08:25:35.5882204Z 70bed83a25c4: Waiting
2024-09-10T08:25:35.5883067Z b8cc3c3a30cf: Waiting
2024-09-10T08:25:35.5883822Z df41b3ea5e95: Waiting
2024-09-10T08:25:35.5884483Z f41993bcef51: Waiting
2024-09-10T08:25:35.6756344Z 7ec3a91b66d9: Verifying Checksum
2024-09-10T08:25:35.6766850Z 7ec3a91b66d9: Download complete
2024-09-10T08:25:35.7244322Z c158987b0551: Verifying Checksum
2024-09-10T08:25:35.7245023Z c158987b0551: Download complete
2024-09-10T08:25:35.8971113Z 2a66ef9569bf: Verifying Checksum
2024-09-10T08:25:35.8972409Z 2a66ef9569bf: Download complete
2024-09-10T08:25:35.8973291Z 51ba2aaea185: Verifying Checksum
2024-09-10T08:25:35.8974257Z 51ba2aaea185: Download complete
2024-09-10T08:25:35.8975214Z 4fe55734f00f: Verifying Checksum
2024-09-10T08:25:35.8976081Z 4fe55734f00f: Download complete
2024-09-10T08:25:35.8977077Z 897ff19824a2: Verifying Checksum
2024-09-10T08:25:35.8977761Z 897ff19824a2: Download complete
2024-09-10T08:25:35.9352835Z 2d2a69b423bd: Verifying Checksum
2024-09-10T08:25:35.9354506Z 2d2a69b423bd: Download complete
2024-09-10T08:25:35.9499248Z c158987b0551: Pull complete
2024-09-10T08:25:35.9539760Z 5b412bbde264: Verifying Checksum
2024-09-10T08:25:35.9540474Z 5b412bbde264: Download complete
2024-09-10T08:25:36.0446002Z 343c503f69a2: Verifying Checksum
2024-09-10T08:25:36.0446589Z 343c503f69a2: Download complete
2024-09-10T08:25:36.1837033Z 4823297a760e: Verifying Checksum
2024-09-10T08:25:36.1837853Z 4823297a760e: Download complete
2024-09-10T08:25:36.2914080Z 70bed83a25c4: Download complete
2024-09-10T08:25:36.3568437Z a4ae34314a30: Verifying Checksum
2024-09-10T08:25:36.3569547Z a4ae34314a30: Download complete
2024-09-10T08:25:36.4004734Z b8cc3c3a30cf: Verifying Checksum
2024-09-10T08:25:36.4011097Z b8cc3c3a30cf: Download complete
2024-09-10T08:25:36.4554408Z df41b3ea5e95: Verifying Checksum
2024-09-10T08:25:36.4556153Z df41b3ea5e95: Download complete
2024-09-10T08:25:36.5353651Z f41993bcef51: Verifying Checksum
2024-09-10T08:25:36.5355527Z f41993bcef51: Download complete
2024-09-10T08:25:36.6066802Z cb6ed86980e0: Verifying Checksum
2024-09-10T08:25:36.6068225Z cb6ed86980e0: Download complete
2024-09-10T08:25:37.3050299Z 7ec3a91b66d9: Pull complete
2024-09-10T08:25:37.8657546Z 2a66ef9569bf: Pull complete
2024-09-10T08:25:37.8816214Z 51ba2aaea185: Pull complete
2024-09-10T08:25:38.1602647Z 4fe55734f00f: Pull complete
2024-09-10T08:25:39.9103586Z cb6ed86980e0: Pull complete
2024-09-10T08:25:39.9265083Z 897ff19824a2: Pull complete
2024-09-10T08:25:39.9411060Z 2d2a69b423bd: Pull complete
2024-09-10T08:25:39.9535537Z 5b412bbde264: Pull complete
2024-09-10T08:25:46.0748285Z a4ae34314a30: Pull complete
2024-09-10T08:25:46.0977406Z 343c503f69a2: Pull complete
2024-09-10T08:25:46.1131742Z 4823297a760e: Pull complete
2024-09-10T08:25:46.1225672Z 70bed83a25c4: Pull complete
2024-09-10T08:25:46.1306341Z b8cc3c3a30cf: Pull complete
2024-09-10T08:25:46.1400148Z df41b3ea5e95: Pull complete
2024-09-10T08:25:46.1493071Z f41993bcef51: Pull complete
2024-09-10T08:25:46.1530162Z Digest: sha256:0515ccfc1fadc9cd7ecc0bb825f2644309ee37857b1a60ac75c8401e3533ea1e
2024-09-10T08:25:46.1557700Z Status: Downloaded newer image for deloo/markdown-docs:0.6.7
2024-09-10T08:25:46.1579677Z docker.io/deloo/markdown-docs:0.6.7
2024-09-10T08:25:46.1591826Z ##[endgroup]
```

I can see that this version is hard-coded in the [action.yml](https://github.com/ldeluigi/markdown-docs/blob/master/action.yml) and hasn't been changed in 2 years.

Could that be the issue here?

**Comment by ldeluigi** [comment] 2024-09-10 09:08
I forgot about that. Thanks and sorry!

**Closed** 2024-09-10 09:12 UTC
